#application.yml
#my.name: ApplicationProperties
server:
  servlet.context-path: /app
  port: 9090

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/basic
    username: sa
    password:
